name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET 9.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore TimedBackgroundJob.sln
      - name: Build solution
        run: dotnet build TimedBackgroundJob.sln --configuration Release --no-restore
      - name: Pack NuGet package
        run: dotnet pack src/TimedBackgroundJob/TimedBackgroundJob.csproj --configuration Release --no-build --output ./nupkg
      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/ChauThan/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
      - name: Notify success
        if: success()
        run: echo "NuGet package published successfully."
      - name: Notify failure
        if: failure()
        run: echo "NuGet package publishing failed."
